config/routes.rb
Rails.application.routes.draw do
  root               'static_pages#home'
  
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :games, except: [:new, :edit]
  
  resources :users do
    get 'search', on: :collection
  end
end

app/models/user.rb
# Represents a user of the application.
class User < ApplicationRecord
  has_secure_password
  has_many :created_games, class_name: "Game", foreign_key: "player1_id",
                           inverse_of: :player1
  has_many :joined_games, class_name: "Game", foreign_key: "player2_id",
                           inverse_of: :player2

  minHandleLength = Rails.configuration.x.minimum_handle_length
  maxHandleLength = Rails.configuration.x.maximum_handle_length
  maxEmailLength  = Rails.configuration.x.maximum_email_address_length
  
  validates :handle,
      presence: true,
        length: { in: minHandleLength..maxHandleLength },
    uniqueness: { case_sensitive: false }
  
  validates :handle, format: {    with: /\A[a-z0-9]/i,
                               message: "must begin with a letter or number" }
  
  validates :handle,
    format: { without: /\W/,
              message: "can contain only letters, numbers, and underscores" }
  
  validates :email,
        presence: true,
          length: { maximum: maxEmailLength },
          format: { with: /.+@.+\..+/ },
      uniqueness: { case_sensitive: false }
  
  # Trim whitespace from relevant user input before validation
  before_validation :trim_whitespace

  # Create a new game.
  def create_game
    created_games.create!
  end
  
  # Join an existing game.
  def join_game(game)
    raise JoiningUserCreatedGameError if self == game.player1
    raise GameAlreadyJoinedError unless game.player2.nil? || self == game.player2
    
    joined_games << game
  end
  
  # Resign from a pending game.
  def resign_from_game(game)
    game.resign self
  end
  
  # Get user game record (wins, losses, etc.). If player is specified, get game
  # record against player.
  def game_record(player = nil)
    record = {
      wins: 0,
      losses: 0,
      draws: 0,
      pending_games: 0,
      games_created: 0,
      games_joined: 0,
      games_played: 0
    }
    tally_created_games record, player
    tally_joined_games record, player
    record[:games_played] = record[:games_created] + record[:games_joined]
    return record
  end
  
  # Get all games in which user is a participant, sorted in descending order
  # by time last updated.
  def all_games
    (created_games + joined_games).sort_by! { |game| game.updated_at }.reverse!
  end
  
  # Get user's ongoing games, sorted in descending order by time last updated.
  def ongoing_games
    all_games.select { |game| game.ongoing? }
  end
  
  # Get user's completed games, sorted in descending order by time last updated and
  # optionally limited to a given number of games.
  def completed_games(limit = nil)
    result = all_games.select { |game| game.completed? }
    result = result.take(limit) if limit
    result
  end
  
  # Get user's waiting game, or return nil if absent.
  def waiting_game
    created_games.find { |game| game.waiting? }
  end
  
  # Determine whether user is a player in the given game.
  def is_player_in?(game)
    [game.player1_id, game.player2_id].include? id
  end
  
  private
    
    # Account for created games in record
    def tally_created_games(record, player)
      created_games.each do |game|
        if player.nil? || game.player2_id == player.id
          case game.status
          when Game::P1_WON, Game::P2_FORFEIT
            record[:wins] += 1
          when Game::P2_WON, Game::P1_FORFEIT
            record[:losses] += 1
          when Game::DRAW
            record[:draws] += 1
          when Game::PENDING
            record[:pending_games] += 1
          end
          record[:games_created] += 1
        end
      end
    end
    
    # Account for joined games in record
    def tally_joined_games(record, player)
      joined_games.each do |game|
        if player.nil? || game.player1_id == player.id
          case game.status
          when Game::P2_WON, Game::P1_FORFEIT
            record[:wins] += 1
          when Game::P1_WON, Game::P2_FORFEIT
            record[:losses] += 1
          when Game::DRAW
            record[:draws] += 1
          when Game::PENDING
            record[:pending_games] += 1
          end
          record[:games_joined] += 1
        end
      end
    end
    
    # Trim whitespace from relevant user input
    def trim_whitespace
      self.handle = handle.try(:strip)
      self.email = email.try(:strip)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, only: [:edit, :update, :destroy]
  skip_before_action :require_login, only: [:new, :create]

  # GET /users
  def index
  end

  # GET /users/1
  # GET /users/1.json
  def show
    current_user = user_session.current_user
    @pair_record = current_user.game_record(@user) unless @user.id == current_user.id
    @full_record = @user.game_record
  end

  # GET /users/new
  def new
    if user_session.logged_in?
      redirect_to games_url
    else
      @user = User.new
      render layout: 'cover'
    end
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        user_session.log_in @user
        format.any(:html, :js) { redirect_to games_url }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, layout: 'cover' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.any(:html, :js) do
          flash[:success] = "Your settings have been updated."
          redirect_to @user
        end
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    user_session.log_out
    respond_to do |format|
      format.html do
        flash[:success] = "Your account has been deleted."
        redirect_to root_url
      end
      format.json { head :no_content }
    end
  end
  
  # Search for a user by handle or by email address.
  #
  # GET /users/search
  # GET /users/search.json
  def search
    query = params[:query]
    
    # If the query includes an "@," search by email address, otherwise search by handle.
    # The search is case-insensitive. Since the handles and email addresses are stored
    # in the database in their original forms, without first being converted to
    # lowercase, it is necessary to convert them to lowercase during the search.
    # This involves full-table scans, which would be inefficient for larger tables,
    # but are of no consequence to this application.
    if query.include? '@'
      @user = User.find_by 'LOWER(email) = LOWER(?)', query
    else
      @user = User.find_by 'LOWER(handle) = LOWER(?)', query
    end
    
    respond_to do |format|
      if @user
        format.html { redirect_to @user }
        format.json { render :show }
      else
        format.html do
          @user_not_found = true
          render :index
        end
        format.json { head :not_found }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:handle, :email, :password, :password_confirmation)
    end
    
    # Allow access only to the current user.
    def authorize_user
      head :forbidden unless @user.id == user_session.current_user.id
    end
end

app/helpers/users_helper.rb
module UsersHelper
  # Get a Gravatar image tag for a user and context.
  def gravatar_image_tag(user, context = nil)
    context = context.try(:to_sym)
    
    case context
    when :profile
      size = 350
      img_alt = user.handle
    when :nav
      size = 28
      img_alt = ""
    else
      size = 80
      img_alt = user.handle
    end
    
    email = user.nil? ? "" : user.email
    
    image_tag avatar_url(email, size),
                          class: 'avatar img-responsive img-rounded center-block',
                          alt: img_alt
  end
  
  private
  
    # Get URL of Gravatar of given size for given email address.
    def avatar_url(email, size)
      "https://www.gravatar.com/avatar/#{ email_hash(email) }?s=#{ size }"
    end
    
    # Get hash of given email address for use in Gravatar URL.
    def email_hash(email)
      Digest::MD5.hexdigest email.downcase
    end
end

app/views/users/_form.html.erb
<%= bootstrap_form_for @user, remote: true, format: :js, inline_errors: true do |f| %>
  <%= f.text_field :handle, hide_label: true, placeholder: 'Username' %>
  <% # May need this this later for tooltip
    <<-LABEL.html_safe
      <span class="glyphicon glyphicon-question-sign" aria-hidden="true"
            data-toggle="tooltip" data-placement="auto right"
            title="#{ Rails.configuration.x.minimum_handle_length }–#{ Rails.configuration.x.maximum_handle_length } alphanumeric characters">
      </span>
      LABEL
  %>
  <%= f.email_field :email, hide_label: true, placeholder: 'Email address' %>
  <%= f.password_field :password, hide_label: true, placeholder: 'Password' %>
  <%= f.password_field :password_confirmation, hide_label: true,
                                               placeholder: 'Confirm password' %>
  <%= f.form_group do %>
    <%= f.submit @user.new_record? ? 'Sign up' : 'Update',
                 class: 'btn btn-lg btn-primary btn-block' %>
  <% end %>
<% end %>

app/views/users/create.js.erb
$('.new_user').replaceWith('<%=j render 'form' %>')

app/views/users/edit.html.erb
<% content_for :title do -%>
  <%= 'Settings' %>
<% end -%>

<div class="row">
  <div class="col-sm-6">
    <%= gravatar_image_tag(@user, :profile) %>
  </div>
  <div class="col-sm-6">
    <h2 class="text-center"><%= 'Your account' %></h2>
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<% content_for :title do -%>
  User Lookup
<% end -%>

<div class="row">
  <div class="col-sm-4 col-sm-offset-4">
    <h2>User lookup</h2>
    <%= bootstrap_form_tag url: search_users_path, method: :get do |f| %>
      <%= f.search_field :query, id: 'user-query', label: "Username or email address",
                                               autofocus: true %>
      <%= f.form_group do %>
        <%= f.submit 'Submit' %>
      <% end %>
      <% if @user_not_found -%>
        <p class="text-danger">User not found</p>
      <% end -%>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% content_for :title do -%>
  <%= 'Sign up' %>
<% end -%>

<h1 class="cover-heading sr-only">Create account</h1>

<div class="new-user-content form-content">
  <%= render 'form' %>
  
  <p class="foot-notice">
    Have an account? <%= link_to 'Log in', login_path %>
  </p>
</div>

app/views/users/show.html.erb
<% content_for :title do -%>
  <%= @user.handle %>
<% end -%>

<div class="row">
  <div class="col-sm-6">
    <%= gravatar_image_tag(@user, :profile) %>
    <% if @user == user_session.current_user -%>
      <p class="change-profile-picture"><%= link_to 'Change profile picture',
                                         'https://en.gravatar.com/', target: :blank %></p>
    <% end -%>
  </div>
  <div class="col-sm-6">
    <h2 class="text-center"><%= @user.handle %></h2>
    <% if @pair_record -%>
      <h3><%= pair_record_title(@user) %></h3>
      <%= render partial: 'record_list', object: @pair_record %>
    <% end -%>
    <h3><%= full_record_title(@user) %></h3>
    <%= render partial: 'record_list', object: @full_record %>
  </div>
</div>

app/views/users/update.js.erb
$('.edit_user').replaceWith('<%=j render 'form' %>')