config/routes.rb
Rails.application.routes.draw do
  root               'static_pages#home'
  
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :games, except: [:new, :edit]
  
  resources :users do
    get 'search', on: :collection
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| -%>
  <%= content_tag :div, class: "alert alert-#{ name } alert-dismissible",
                         role: "alert" do %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= msg %>
  <% end %>
<% end -%>

app/views/layouts/_head.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>

app/views/layouts/_head_top.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

app/views/layouts/_main_nav.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
              data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Tic-Tac-Toe', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= nav_link 'Games', games_path %>
        <%= nav_link 'Users', users_path %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                            aria-haspopup="true" aria-expanded="false">
            <%= gravatar_image_tag user_session.current_user, :nav %>
            <%= user_session.current_user.handle %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Profile', user_path(user_session.current_user) %></li>
            <li><%= link_to 'Settings', edit_user_path(user_session.current_user) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Log out', logout_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'layouts/head_top' %>
  <title>
    <% if content_for?(:title) -%>
      <%= yield :title %> |
    <% end -%>
    Tic-Tac-Toe
  </title>
  <%= render 'layouts/head' %>
</head>
<body>
  <%= render 'layouts/main_nav' %>
  <div class="container">
    <%= render 'layouts/flash' %>
    <%= yield %>
  </div>
  
  <script>
    App.User.id = <%= user_session.current_user.id %>;
  </script>
  
  <!-- Templates -->
  
  <script type="text/template" id="play-again-request-template">
    <%= render 'games/play_again_request' %>
  </script>
  
  <script type="text/template" id="play-again-status-template">
    <%= render 'games/play_again_status' %>
  </script>
</body>
</html>

app/views/layouts/cover.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head_top' %>
    <title>
      <% if content_for?(:title) -%>
        <%= yield :title %> |
      <% end -%>
      Tic-Tac-Toe
    </title>
    <%= render 'layouts/head' %>
  </head>
  <body class="cover-body">
    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Tic-Tac-Toe</h3>
              <nav>
                <ul class="nav masthead-nav">
                  <%= nav_link 'Home', root_path %>
                  <%= nav_link 'Sign up', new_user_path %>
                  <%= nav_link 'Login', login_path %>
                </ul>
              </nav>
            </div>
          </div>

          <div class="inner cover">
            <%= render 'layouts/flash' %>
            <%= yield %>
          </div>

          <div class="mastfoot">
            <div class="inner">
              <p><!-- footer --></p>
            </div>
          </div>

        </div>

      </div>

    </div>
  </body>
</html>